export default {
  INSERT: {
    FRAME: "INSERT_FRAME",
    IMAGE: "INSERT IMAGE",
    TEXT: "INSERT_TEXT",
    SHAPE: "INSERT SHAPE",
    ICON: "INSERT ICON",
    SPECIAL_ICON: "INSERT SPECIAL_ICON",
    LINE: "INSERT LINE",
  },
};
